CREATE TABLE Room (
	RoomID INTEGER PRIMARY KEY AUTOINCREMENT,
	RoomNo VARCHAR(10) NOT NULL,
	FloorLevel VARCHAR(10) NOT NULL,
	RoomType VARCHAR(20) NOT NULL,
	WeeklyRate DECIMAL(10,2) NOT NULL,
	MonthlyRate DECIMAL(10,2) NOT NULL,
	SecurityDeposit DECIMAL(10,2),
	IsAvailable TEXT NOT NULL DEFAULT 1
);

CREATE TABLE Booking (
	BookingID INTEGER PRIMARY KEY AUTOINCREMENT,
	GuestID INT NOT NULL,
	RoomID INT NOT NULL,
	BookingDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CheckInDate DATE NOT NULL,
	CheckOutDate DATE NOT NULL,
	Status VARCHAR(20) NOT NULL,
	TotalAmout DECIMAL(10,2),
	SecurityDepositPaid TEXT DEFAULT 0,
	FOREIGN KEY (GuestID) REFERENCES Guest(GuestID),
	FOREIGN KEY (RoomID) REFERENCES Room(RoomID)
);

CREATE TABLE Payment (
	PaymentID INTEGER PRIMARY KEY AUTOINCREMENT,
	GuestID INT NOT NULL,
	RoomID INT NOT NULL,
	BookingID INT NOT NULL,
	PaymentDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Amount DECIMAL(10,2) NOT NULL,
	PayMethod VARCHAR(30) NOT NULL,
	Status VARCHAR(20) NOT NULL,
	LateFeeApplied INT DEFAULT 0,
	LateFeeAmount DECIMAL(10,2),
	FOREIGN KEY (GuestID) REFERENCES Guest(GuestID),
	FOREIGN KEY (RoomID) REFERENCES Room(RoomID),
	FOREIGN KEY (BookingID) REFERENCES Booking(BookingID)
);
