CREATE TABLE Service (
	ServiceID INTEGER PRIMARY KEY AUTOINCREMENT,
	ServiceName VARCHAR(50) UNIQUE,
	Availability VARCHAR(50),
	ServicePrice VARCHAR(50)
);

CREATE TABLE ServiceRequest (
	RequestID INTEGER PRIMARY KEY AUTOINCREMENT,
	ServiceID INT NOT NULL,
	GuestID INT NOT NULL,
	RoomID INT NOT NULL,
	RequestDetails TEXT NOT NULL,
	RequestDate DATETIME NOT NULL,
	Status VARCHAR(50) NOT NULL DEFAULT 'Pending',
	Cost DECIMAL(10,2),
	FOREIGN KEY (ServiceID) REFERENCES Service(ServiceID),
	FOREIGN KEY (GuestID) REFERENCES Guest(GuestID),
	FOREIGN KEY (RoomID) REFERENCES Room(RoomID)
);

CREATE TABLE MealPlan (
	PlanID INTEGER PRIMARY KEY AUTOINCREMENT,
	PlanName VARCHAR(50),
	PlanPrice DECIMAL(10,2) NOT NULL
);

CREATE TABLE MealSubscription (
	SubscriptionID INTEGER PRIMARY KEY AUTOINCREMENT,
	GuestID INT NOT NULL,
	PlanID INT NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE,
	Status VARCHAR(20) NOT NULL DEFAULT 'Pending', 
	FOREIGN KEY (GuestID) REFERENCES Guest(GuestID),
	FOREIGN KEY (PlanID) REFERENCES MealPlan(PlanID)
);

CREATE TABLE Visitor (
	VisitorID INTEGER PRIMARY KEY AUTOINCREMENT,
	VisitorName VARCHAR(100) NOT NULL,
	IDType VARCHAR(50) NOT NULL,
	NumberOfID VARCHAR(50) NOT NULL,
	VisitPurpose TEXT NOT NULL
);

CREATE TABLE VisitorLog (
	LogID INTEGER PRIMARY KEY AUTOINCREMENT,
	VisitorID INT NOT NULL,
	GuestID INT NOT NULL,
	RoomID INT NOT NULL,
	TimeIn DATETIME NOT NULL,
	TimeOut DATETIME NOT NULL,
	GuestApprovalStatus VARCHAR(20) NOT NULL DEFAULT 'Pending',
	FOREIGN KEY (VisitorID) REFERENCES Visitor(VisitorID),
	FOREIGN KEY (GuestID) REFERENCES Guest(GuestID),
	FOREIGN KEY (RoomID) REFERENCES Room(RoomID)
);

CREATE TABLE Announcement(
	AnnouncementID INTEGER PRIMARY KEY AUTOINCREMENT,
	Title VARCHAR(150) NOT NULL,
	AnnouncmentType VARCHAR(30) NOT NULL,
	AnnouncementDate DATETIME NOT NULL,
	Description TEXT NOT NULL
);