CREATE TABLE User (
	UserID INTEGER PRIMARY KEY AUTOINCREMENT,
	FirstName VARCHAR (50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	Email VARCHAR(50) UNIQUE NOT NULL,
	TelNo VARCHAR(11) UNIQUE NOT NULL,
	Role VARCHAR(100) NOT NULL,
	Password VARCHAR(20) NOT NULL
);

CREATE TABLE Guest (
	GuestID INTEGER PRIMARY KEY AUTOINCREMENT,
	UserID INT NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	Email VARCHAR(50) UNIQUE NOT NULL,
	TelNo VARCHAR(11) UNIQUE NOT NULL,
	Address TEXT NOT NULL,
	IDProofType VARCHAR(50) NOT NULL,
	IDNumber VARCHAR(20) NOT NULL,
	Occupation VARCHAR(50),
	DOB DATE NOT NULL,
	EmergencyContactName VARCHAR(100),
	EmergencyContactRelationship VARCHAR(50),
	EmergencyContactNumber VARCHAR(20),
	FOREIGN KEY (UserID) REFERENCES User(UserID)
);